Libraries

In [2]:
import numpy as np 
import pandas as pd
from sklearn import preprocessing

/var/folders/vx/hcp7x2k56qj24ksjy2vx2vlr0000gn/T/ipykernel_37975/3856780930.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


1.3.1

In [2]:
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


1.3.2

In [7]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


1.3.3

In [8]:

array = np.random.rand(3,3,3)
print(array)

[[[0.77845161 0.48939237 0.40686039]
  [0.00290982 0.21276426 0.78948469]
  [0.17013213 0.347991   0.31842629]]

 [[0.06774314 0.99332523 0.96554712]
  [0.98093295 0.8045964  0.4290665 ]
  [0.46329559 0.15187629 0.24129271]]

 [[0.03437548 0.88123493 0.40668504]
  [0.01822032 0.47561432 0.99787184]
  [0.4739177  0.55558034 0.0891846 ]]]


1.3.4

In [9]:

n = 5
matrix = np.ones((n, n))
matrix [1:-1, 1:-1] = 0
print(matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


1.3.5

In [3]:
arr = np.array([54, 12, 45, 645, 324, 123])
sortedarr = np.sort(arr)[::-1]
print(sortedarr)

[645 324 123  54  45  12]


1.3.6

In [4]:
n = int(input())
m = int(input())

A = np.random.random((n,m))
if len(A) == 0 or (len(A[0])) == 0:
  print("Матрица не существует!")
elif len(A) == (len(A[0])):
  print("Квадратная матрица\nРазмер: ", len(A)*(len(A[0])),"\nРазмерность: ", len(A), "x", (len(A[0])))
elif len(A) != (len(A[0])):
  print("Прямоугольная матрица\nРазмер: ", len(A)*(len(A[0])),"\nРазмерность: ", len(A), "x", (len(A[0])))

Квадратная матрица
Размер:  9 
Размерность:  3 x 3


2.3.1

In [5]:
def euclideandistance(a, b):
    if len(a) != len(b):
        return None
    
    sumofsquares = np.sum((a - b) ** 2)
    
    return np.sqrt(sumofsquares)

# Пример использования
a = pd.Series([1, 2, 3])
b = pd.Series([4, 5, 6])

distance = euclideandistance(a, b)
print(distance)

5.196152422706632


2.3.2

In [6]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
print(dataframe.head())

   stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer


2.3.3

In [7]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/FMLPDA_Table4_3.csv'
dataframe = pd.read_csv(url)
print(dataframe)
print("\n")
#2.2.5
print(dataframe.head(2))
print("\n")
print(dataframe.tail(3))
print("\n")
print(dataframe.shape)
print("\n")
print(dataframe.describe())
print("\n")
#2.2.6
print(dataframe.iloc[2:4])
print("\n")
#2.2.7
print(dataframe[dataframe['slope'] == 'steep'].head())

   stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian
2    True     steep    medium   riparian
3   False     steep    medium  chapparal
4   False      flat      high    conifer
5    True     steep   highest    conifer
6    True     steep      high  chapparal


   stream     slope elevation vegetation
0   False     steep      high  chapparal
1    True  moderate       low   riparian


   stream  slope elevation vegetation
4   False   flat      high    conifer
5    True  steep   highest    conifer
6    True  steep      high  chapparal


(7, 4)


       stream  slope elevation vegetation
count       7      7         7          7
unique      2      3         4          3
top      True  steep      high  chapparal
freq        4      5         3          3


   stream  slope elevation vegetation
2    True  steep    medium   riparian
3   False  steep    medium  chapparal


   stream  slope elevation vegetation
0   False  steep

In [8]:
from sklearn import preprocessing

url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)

min_max_scaler = preprocessing.MinMaxScaler()
dataframe['sepal_length_cm'] = min_max_scaler.fit_transform(dataframe[['sepal_length_cm']])

z_score_scaler = preprocessing.StandardScaler()
dataframe['sepal_width_cm'] = z_score_scaler.fit_transform(dataframe[['sepal_width_cm']])

print(dataframe['sepal_length_cm'], "\n")
print(dataframe['sepal_width_cm'])

0      0.222222
1      0.166667
2      0.111111
3      0.083333
4      0.194444
         ...   
145    0.666667
146    0.555556
147    0.611111
148    0.527778
149    0.444444
Name: sepal_length_cm, Length: 150, dtype: float64 

0      1.032057
1     -0.124958
2      0.337848
3      0.106445
4      1.263460
         ...   
145   -0.124958
146   -1.281972
147   -0.124958
148    0.800654
149   -0.124958
Name: sepal_width_cm, Length: 150, dtype: float64
